name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, curl, zip, bcmath, gd, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Create deployment artifact
        run: tar -czf ../app.tar.gz --exclude='.git' --exclude='node_modules' --exclude='tests' .

      - name: Move artifact
        run: mv ../app.tar.gz .

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: "/tmp/"

      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Navigate to web directory
            cd /var/www/laravel

            # Backup current version
            if [ -d "current" ]; then
              timestamp=$(date +%Y%m%d_%H%M%S)
              mv current "backup_${timestamp}"
              # Keep only last 3 backups
              ls -dt backup_* | tail -n +4 | xargs rm -rf
            fi

            # Create new release directory
            mkdir -p releases/$(date +%Y%m%d_%H%M%S)
            cd releases/$(date +%Y%m%d_%H%M%S)

            # Extract new code
            tar -xzf /tmp/app.tar.gz
            rm /tmp/app.tar.gz

            # Copy .env file from previous release or shared
            if [ -f "/var/www/laravel/shared/.env" ]; then
              cp /var/www/laravel/shared/.env .env
            fi

            # Create shared storage link
            rm -rf storage
            ln -s /var/www/laravel/shared/storage storage

            # Set permissions
            chmod -R 775 bootstrap/cache

            # Run Laravel commands
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force

            # Create symlink to current release
            cd /var/www/laravel
            ln -sfn releases/$(ls -t releases | head -1) current

            # Set final permissions
            sudo chown -R deploy:www-data /var/www/laravel/current
            sudo chmod -R 775 /var/www/laravel/current/bootstrap/cache

            # Reload PHP-FPM
            sudo systemctl reload php8.3-fpm

            echo "Deployment completed successfully!"
